style.css

css file for the Portfolio

---

index.html

Adding CV Download button

---

index.html

Updated & Correction of Some Errors

Correction of Some Errors

---

index.html

Modal Implementation

---

index.html

Updating New Project

---

index.html

Updating Projects

---

index.html

Update some new Projects

---

style.css

Updating Style

---

index.html

updating index

---

index.html

Updating Skills

---

index.html

updating UI and Adding Projects
ToDo-Task-App - MERN Stack Project Added

updating UI and Adding Projects

---

index.html

updating some Links

---

style.css

updating Styles

---

src/App.scss
src/RouterComponent.js
src/assets/data/experiencesData.json

Home Page as a Landing Page (contains all the Pages)

---

src/App.js
src/RouterComponent.js
src/assets/navLinks.js
src/components/Academics/Academics.js
src/components/Footer/Footer.js
src/components/Header/Header.js

Footer section Added

---

public/index.html
src/components/Academics/Academics.js
src/components/Footer/Footer.js
src/components/Header/Header.js
src/components/SharedComponents/ActiveStatusGreenDot/Logo.jsx

'N_Ah' name replaced by Logo

---

src/assets/data/skillsData.json
src/components/Skills/Skills.js
src/components/Skills/SkillsPopover.js
src/components/Skills/Tech/Tech.jsx
src/components/Skills/skills.css

Added Skills popover to show Projects

---

src/components/Experiences/DesktopViewExperience.js
src/helpers/generateNumber.js

Experience Section update in Desktop Screen

---

src/assets/data/academicsData.json
src/components/Academics/Academics.js
src/components/SharedComponents/Modal/Modal.js
src/components/SharedComponents/Modal/modal.css
src/styles.css

External Links are in Modal

---

src/assets/data/experiencesData.json
src/components/Experiences/DesktopViewExperience.js
src/components/SharedComponents/ActiveStatusGreenDot/SkillDiv.js

company skills section Fix

---

src/styles.css

Download CV btn Fix

---

src/components/Header/Header.js

Active nav link style fix

---

public/icons/curvy-lines.svg
src/components/Academics/Academics.js
src/components/Experiences/Experiences.js
src/components/Projects/Projects.js
src/components/SharedComponents/SectionHeader/SectionHeader.js
src/components/SharedComponents/SectionHeader/section-header.css
src/components/SharedComponents/index.js
src/components/Skills/Skills.js

V4.3 change section header #88

---

src/components/Experiences/Experiences.js
src/components/Experiences/experience.scss

Experience timeline UI fix

---

src/components/Projects/Projects.js
src/components/SharedComponents/SkillsView.js

Skills section color fixes

---

src/components/Profile/ProfilePicture/ProfilePicture.js

changes on width and height

---

src/assets/data/projectsData.json
src/components/Profile/ProfilePicture/ProfilePicture.js
src/components/Profile/ProfilePicture/profilePicture.scss

##Profile picture border animations

Hero pic border animation

---

src/components/Profile/ProfilePicture/profilePicture.scss

pause hero pic border animation in mobile screen.

---

src/App.scss
src/RouterComponent.js
src/components/Header/Header.js
src/components/Profile/Profile.js
src/styles.css

Nav-Bar top fixed while  scrolling
> Desktop 💻 View
> Mobile 📱 View

Nav-Bar top fixed on scroll

---

src/components/Projects/Projects.js
src/styles.css

Projects section UI changes

---

src/components/Profile/ProfileText/ProfileText.js
src/components/Profile/ProfileText/profileText.scss

text color gradient
